version: '3.3'
services:
  checkpoint:
    container_name: checkpoint-server
    image: csunmetalab/environment:checkpoint
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
  composer:
    container_name: composer-install
    image: composer:latest
    command: install
    volumes:
      - .:/app
  db:
    container_name: checkpoint-mysql
    image: mysql:5.6.41
    volumes:
      - db_data:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: checkpoint
      MYSQL_DATABASE: checkpoint  
      MYSQL_USER: checkpoint
      MYSQL_PASSWORD: checkpoint
  adminer:
    container_name: checkpoint-adminer
    image: adminer:latest
    ports:
      - 8081:8080

volumes:
    db_data: